### ISSUE TITLE
Πολυωνυμικοί συντελεστές Ci, Di για αντίστροφα πολυώνυμα x=x(E,N), y=y(E,N)

### ISSUE THREAD

**Issue by hatziliontos** [georgeouzou/survgr#31]
Καλημέρα, έχω υπολογίσει τους συντελεστές Ci, Di στα πολυώνυμα x=C0+C1*E+C2*N+C3*E*E+C4*N*N+C5*E*N και y=D0+D1*E+D2*N+D3*E*E+D4*N*N+D5*E*N, δηλαδή μετατροπή από ΕΓΣΑ87 σε HATT (για κάθε φύλλο ξεχωριστά, 390 φύλλα). Πριν προωθήσω τους συντελεστές στην ακαδημαϊκή κοινότητα για ελέγχους, μίλησα με κ. Πικριδά για το αν γνωρίζει κάποιον που να έχει κάνει ήδη αυτή την δουλειά και μου ανέφερε ότι ο κ. Κατσάμπαλος είχε πιθανά ασχοληθεί στο παρελθόν αλλά ανέφερε και το survo.gr. Έριξα μια ματιά στους κώδικες που κατασκεύασες εδώ στο github όμως δεν είδα συντελεστές πέρα από τους παλιούς γνωστούς του ΟΚΧΕ για μετατροπή από HATT σε ΕΓΣΑ87. Βέβαια διαπίστωσα ότι χρησιμοποιείς την βιβλιοθήκη proj4 με ενσωματωμένους τους συντελεστές ΟΚΧΕ και μάλλον το proj4 αναλαμβάνει να κάνει την αντιστροφή των συντεταγμένων. Μπορείς να επιβεβαιώσεις την μη χρήση συντελεστών Ci, Di για μετατροπή από ΕΓΣΑ87 σε HATT? Αν θέλεις μπορώ να σου τους στείλω για δοκιμές - ενσωμάτωση στον κώδικα.

Χατζηλιόντος Χριστόδουλος
Διπλ Χημ Μηχ ΕΜΠ
Αγρ. Τοπ. Μηχ. ΑΠΘ (9ο εξ)

**Comment by georgeouzou** [comment]
Καλησπέρα Χριστόδουλε, 

πράγματι, η αντίστροφη μετατροπή από ΕΓΣΑ87 σε HATT γίνεται βάσει επαναληπτικής διαδικασίας, με τους συντελεστές του ΟΚΧΕ. Παλαιότερα ο αλγόριθμος ήταν γραμμένος σε python και αργότερα μετέφερα τον αλγόριθμο στην [proj](https://github.com/OSGeo/PROJ/pull/3133). Τώρα για την ευθεία ή αντίστροφη μετατροπή, απλά στέλνω τους συντελεστές στην proj, με αποτέλεσμα για πολλά σημεία να υπολογίζεται πολύ γρηγορότερα.

Σε αυτό το [commit](https://github.com/georgeouzou/survgr/commit/1a1fc630200bb7718ca7e375931a3d4837d8355e) έγινε η αλλαγή για να χρησιμοποιώ την proj. Ο παλιός αλγόριθμος σε python ήταν [αυτός](https://github.com/georgeouzou/survgr/blob/50da8a3cbfc6775bf18491ab55913dad7d380ad0/transform/hatt/hatt2ggrs.py).

Θα μπορούσαμε, αν ήθελες, να ενσωματώσουμε επιλογή για χρήση των δικών σου υπολογισμένων συντελεστών, για την αντίστροφη μετατροπή.

Γιώργος

**Comment by hatziliontos** [comment]
Καλημέρα Γιώργο,
[H2E-E2H-Gia-Ouzounoudi.xls](https://github.com/user-attachments/files/17615304/H2E-E2H-Gia-Ouzounoudi.xls)
επισυνάπτω πίνακα excel με τους συντελεστές Ci και Di, έχω συγχρονίσει τους παλιούς Ai, Bi με τους δικούς σου και το βιβλίο του ΟΚΧΕ, στο excel έχω βάλει τεστ ποιντ HATT(1000,1500) και βλέπω οι υπολογισμοί ευθέως και αντίστροφα ξαναγυρνούν στο σημείο αυτό σε όλα τα φύλλα. Σου δίνω τους συντελεστές Ci και Di με όλα τα σημαντικά ψηφία από τον υπολογισμό τους χωρίς να έχω κάνει ανάλυση ευαισθησίας για το πόσα από αυτά τα ψηφία χρειάζονται πραγματικά.

Ευχαριστώ
Χριστόδουλος

**Comment by georgeouzou** [comment]
Φαίνεται ότι χρειάζονται αρκετά ψηφία για τα coefficients Ci, Di καθώς οι input συντεταγμένες παίρνουν πολύ μεγάλες τιμές (ΕΓΣΑ87). Ενώ στην ευθεία περίπτωση, όπου οι input συντεταγμένες έχουν σχετικά μικρές τιμές (π.χ. 1000, 1000),
οι Ai και Βi μπορούν να έχουν πολύ λιγότερα σημαντικά ψηφία.

Θα είχε ενδιαφέρον αν οι Ci, Di εφαρμόζονταν αφότου αφαιρούσαμε το κέντρο του κάθε φύλλου (Eo, No) σε ΕΓΣΑ87 δηλαδή:

`x = C0 + C1 * (E-Eo) + C2 * (N-No) + C3 * (E-Eo)^2 + C4 * (N-No)^2 + C5 * (E-Eo) * (N-No)`
`y = D0 + D1 * (E-Eo) + D2 * (N-No) + D3 * (E-Eo)^2 + D4 * (N-No)^2 + D5 * (E-Eo) * (N-No)`

Μάλιστα αυτή φαίνεται να είναι [συνήθης πρακτική](https://proj.org/en/9.5/operations/transformations/horner.html#equation-uv) σε παρόμοιους μετασχηματισμούς άλλων χωρών

**Comment by hatziliontos** [comment]
[H2E-E2H-Gia-Ouzounoudi-v2.xls](https://github.com/user-attachments/files/17692588/H2E-E2H-Gia-Ouzounoudi-v2.xls)
Ωραία πρόταση:
για (x,y)=(0,0) προκύπτει (E0,N0)=(A0,B0), συνεπώς για τα μετατεθειμένα πολυώνυμα ΕΓΣΑ87 σε HATT 
```
x = C1_ * (E-Eo) + C2_ * (N-No) + C3_ * (E-Eo)^2 + C4_ * (N-No)^2 + C5_ * (E-Eo) * (N-No)
y = D1_ * (E-Eo) + D2_ * (N-No) + D3_ * (E-Eo)^2 + D4_ * (N-No)^2 + D5_ * (E-Eo) * (N-No)
```
οι νέοι συντελεστές Ci_, Di_ δίνονται στο επισυναπτόμενο αρχείο και προέκυψαν από τους Ci, Di ως είχαν αυτοί προσδιοριστεί προηγουμένως. Οι τιμές των Ci_, Di_ έχουν αποκοπεί στο ίδιο πλήθος ψηφίων με τους συντελεστές Ai, Bi.

**Comment by georgeouzou** [comment]
Καλησπέρα Χριστόδουλε,

ενσωμάτωσα τους νέους συντελεστές στον κώδικα.

1. [Εδώ](https://github.com/georgeouzou/survgr/commit/21eeb6349bfc0ac597af86b9456993df89b9e50b) έγιναν αλλαγές στον πυρήνα του προγράμματος.
2. [Εδώ](https://github.com/georgeouzou/survgr/commit/2020caae9bf4ee6de3f2d13e74383409561c7401) οι αλλαγές στο user interface και το καινούργιο option.

Έβαλα δοκιμαστικά και τις αλλαγές στο site και αναμένω feedback!

**Comment by hatziliontos** [comment]
Μπράβο Γιώργο, για όποιον θέλει να ελέγξει την εσωτερική ακρίβεια των νέων συντελεστών Ci_, Di_ μπορεί να κάνει αυτό που φαίνεται στα 2 παρακάτω στιγμιότυπα:
1. να ορίσει τυχαία σημεία ΗΑΤΤ σε ένα Φύλλο Χάρτου να αντιγράψει τις υπολογισθείσες συντεταγμένες ΕΓΣΑ87
![image](https://github.com/user-attachments/assets/a9143c66-3c5a-4c29-b60f-8f9ef55fd61a)
2. και να ζητήσει μετατροπή αυτών ξανά σε ΗΑΤΤ με τους νέους συντελεστές
![image](https://github.com/user-attachments/assets/9c341a3b-8855-4171-94a7-053f00e962bb)

Θα διαπιστώσει ότι σε ένα πλαίσιο ελέγχου ΗΑΤΤ (-25000,-25000) έως (+25000,+25000), ο επανυπολογισμός των συντεταγμένων ΗΑΤΤ γίνεται με μια απόκλιση του 1mm για όλη σχεδόν την επιφάνεια εκτός από τις συνοριακές γραμμές που μπορεί να πιάσει 2mm ή 3mm ανάλογα με το φύλλο χάρτη. Αυτή η πολύ καλή εσωτερική ακρίβεια δεν βελτιώνει την εξωτερική ακρίβεια μετατροπής μεταξύ των 2 προβολικών συστημάτων, πρέπει να έχουμε κατά νου ότι υπερισχύει η αβεβαιότητα των 10-15εκ που έδωσε ο ΟΚΧΕ.
